# Generated by Django 3.2.3 on 2021-07-17 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('asin', models.TextField(primary_key=True, serialize=False)),
                ('category', models.TextField()),
                ('duplicateRatio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('incentivizedRatio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ratingAnomalyRate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reviewAnomalyRate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('reviewerID', models.TextField(primary_key=True, serialize=False)),
                ('reviewerName', models.TextField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewID', models.IntegerField(primary_key=True, serialize=False)),
                ('reviewText', models.TextField()),
                ('overall', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('unixReviewTime', models.IntegerField()),
                ('minHash', models.TextField(default='')),
                ('duplicate', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('incentivized', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('asin', models.ForeignKey(db_column='asin', on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('reviewerID', models.ForeignKey(db_column='reviewerID', on_delete=django.db.models.deletion.CASCADE, to='catalog.user')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('reviewerID', 'asin', 'reviewID'), name='unique_review'),
        ),
    ]
