# Generated by Django 3.2.3 on 2021-08-15 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='negativedRatio',
            new_name='negativeRatio',
        ),
    ]
