# Generated by Django 3.2.3 on 2021-06-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_user_reviewername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reviewerName',
            field=models.TextField(),
        ),
    ]
