# Generated by Django 3.2.3 on 2021-07-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
