# Generated by Django 3.2.3 on 2021-06-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_user_reviewername'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='duplicate',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
    ]
