# Generated by Django 3.2.3 on 2021-06-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210625_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewID',
            field=models.IntegerField(default=0),
        ),
    ]
