# Generated by Django 3.2.3 on 2021-06-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_review_reviewid'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='incentivized',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
    ]
